local T       = require("tests.t")
local H       = require("tests.helpers")
local State   = require("engine.state")
local Phases  = require("engine.phases")
local Stamina = require("engine.stamina")

T.test("stamina: full on entering the pitch — strikers 4, midfielders 5, defenders 6, Engine 7", function()
    local m = H.match({ phase = "summon" })
    T.eq(H.place(m, "player", "striker", 1, H.card("striker", 2000, 500)).stamina, 4)
    T.eq(H.place(m, "player", "midfielder", 0, H.card("midfielder", 1500, 1500)).stamina, 5)
    T.eq(H.place(m, "player", "defender", 1, H.card("defender", 900, 1900)).stamina, 6)
    T.eq(H.place(m, "player", "defender", 2, H.kw("ENGINE", "midfielder", 1800, 1500)).stamina, 7)
    T.eq(H.place(m, "player", "keeper", 0, H.card("keeper", 300, 1800), "defense").stamina, nil)
    T.eq(Stamina.max({ type = "trap" }), nil)
    T.eq(Stamina.max(nil), nil)
    local c = H.give(m, "player", H.card("striker", 2100, 500))
    H.store(m):summonCard(c.id, "striker", 2, "defense")
    T.eq(m.players.player.pitch.strikers[2].stamina, 4)
end)

T.test("stamina: each field card on the owner's pitch loses 1 at the end of its owner's turn", function()
    local m = H.match({ phase = "summon" })
    local s  = H.place(m, "player", "striker", 1, H.card("striker", 2000, 500))
    local k  = H.place(m, "player", "keeper", 0, H.card("keeper", 300, 1800), "defense")
    local fd = H.place(m, "player", "defender", 1, H.card("defender", 900, 1900), "defense")
    local o  = H.place(m, "opponent", "striker", 1, H.card("striker", 2000, 500))
    Phases.endTurn(m)
    T.eq(s.stamina, 3); T.eq(fd.stamina, 5); T.eq(k.stamina, nil)
    T.eq(o.stamina, 4, "the other side keeps its stamina")
    Phases.endTurn(m)
    T.eq(o.stamina, 3); T.eq(s.stamina, 3)
end)

T.test("stamina: never below 0; card_tired is logged once, when the card reaches 0", function()
    local m = H.match()
    local s = H.place(m, "player", "striker", 1, H.card("striker", 2000, 500))
    s.stamina = 1
    Phases.endTurn(m); Phases.endTurn(m)
    T.eq(s.stamina, 0)
    Phases.endTurn(m); Phases.endTurn(m)
    T.eq(s.stamina, 0)
    local e = H.events(m, "card_tired")
    T.eq(#e, 1); T.eq(e[1].payload.player, "player"); T.eq(e[1].payload.card, s.definition.id)
    T.eq(e[1].payload.name, s.definition.name); T.eq(e[1].payload.hidden, false)
    T.ok(Stamina.tired(s))
end)

T.test("stamina: attacking costs 1 more when the attack resolves — a fight, a shot, a wasted attack", function()
    local m = H.match()
    local a   = H.place(m, "player", "striker", 1, H.card("striker", 2000, 500))
    local b   = H.place(m, "player", "striker", 2, H.card("striker", 2400, 500))
    local mid = H.place(m, "player", "midfielder", 0, H.card("midfielder", 1500, 1500))
    H.place(m, "opponent", "defender", 1, H.card("defender", 900, 1800), "defense")
    H.place(m, "opponent", "keeper", 0, H.card("keeper", 300, 1800), "defense")
    local s = H.store(m)
    T.eq(s:declareAttack(H.slot("striker", 1), H.slot("defender", 1)).outcome, "defender_destroyed")
    T.eq(a.stamina, 3, "fight")
    s:declareAttack(H.slot("striker", 2), H.slot("keeper"))
    T.eq(b.stamina, 3, "shot")
    local r = s:declareAttack(H.slot("midfielder"), H.slot("midfielder"))
    T.eq(r.outcome, "wasted"); T.eq(mid.stamina, 4, "wasted attack")
end)

T.test("stamina: covering costs the coverer 1, won or lost (last-ditch tackle); the attacker pays too", function()
    local m = H.match({ active = "opponent" })
    local atk = H.place(m, "opponent", "striker", 1, H.card("striker", 2200, 500))
    local mid = H.place(m, "player", "midfielder", 0, H.card("midfielder", 1500, 1500))
    H.place(m, "player", "defender", 2, H.card("defender", 900, 1900), "defense")
    H.place(m, "player", "keeper", 0, H.card("keeper", 300, 1800), "defense")
    local s = H.store(m)
    local r = s:declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    T.eq(r.outcome, "cover_needed")
    r = s:resolveCover({ type = "midfielder", index = 0 })
    T.eq(r.outcome, "tackled")
    T.eq(mid.stamina, 4, "lost cover")
    T.eq(atk.stamina, 3, "the attack resolved")

    local m2 = H.match({ active = "opponent" })
    H.place(m2, "opponent", "striker", 1, H.card("striker", 1400, 500))
    local mid2 = H.place(m2, "player", "midfielder", 0, H.card("midfielder", 1500, 1600))
    H.place(m2, "player", "defender", 2, H.card("defender", 900, 1900), "defense")
    local s2 = H.store(m2)
    s2:declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    r = s2:resolveCover({ type = "midfielder", index = 0 })
    T.eq(r.outcome, "attacker_exhausted")
    T.eq(mid2.stamina, 4, "won cover")
end)

T.test("stamina: Press costs its card 1 more when it fires, nothing when there is no target", function()
    local m = H.match({ phase = "summon" })
    H.place(m, "opponent", "defender", 1, H.card("defender", 900, 1900))
    local c = H.give(m, "player", H.kw("PRESS", "striker", 2100, 700))
    H.store(m):summonCard(c.id, "striker", 1, "attack")
    T.eq(m.players.player.pitch.strikers[1].stamina, 3)
    local m2 = H.match({ phase = "summon" })
    local c2 = H.give(m2, "player", H.kw("PRESS", "striker", 2100, 700))
    H.store(m2):summonCard(c2.id, "striker", 1, "attack")
    T.eq(m2.players.player.pitch.strikers[1].stamina, 4)
end)

T.test("stamina: Counter-press costs its card 1 more when it fires (2 in all for that cover)", function()
    local m = H.match({ active = "opponent" })
    H.place(m, "opponent", "striker", 1, H.card("striker", 1500, 500))
    local cp = H.place(m, "player", "midfielder", 0, H.kw("COUNTER_PRESS", "midfielder", 1700, 1400))
    H.place(m, "player", "defender", 2, H.card("defender", 900, 1900), "defense")
    local s = H.store(m)
    s:declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    local r = s:resolveCover({ type = "midfielder", index = 0 })
    T.eq(r.outcome, "attacker_exhausted")
    T.eq(cp.stamina, 3)
end)

T.test("stamina: an attack cancelled by Offside costs nothing; a Direct Free Kick shooter pays 1", function()
    local m = H.match()
    local a = H.place(m, "player", "striker", 1, H.card("striker", 2000, 500))
    H.place(m, "opponent", "defender", 1, H.card("defender", 900, 1500))
    H.trap(m, "opponent", "trap-offside")
    local r = H.store(m):declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    T.eq(r.outcome, "offside_cancelled")
    T.eq(a.stamina, 4)

    local m2 = H.match()
    local sh = H.place(m2, "player", "striker", 1, H.card("striker", 2000, 500))
    H.place(m2, "opponent", "keeper", 0, H.card("keeper", 300, 1800), "defense")
    local card = H.give(m2, "player", H.def("strat-direct-free-kick"))
    H.store(m2):playStrategy(card.id)
    T.eq(sh.stamina, 3)
end)

T.test("stamina: a new half starts with an empty pitch; cards entering later are fully rested", function()
    local m = H.match({ phase = "summon" })
    local s = H.place(m, "player", "striker", 1, H.card("striker", 2000, 500))
    s.stamina = 0
    State.endHalf(m, "player", "time")
    T.eq(m.players.player.pitch.strikers[1], nil)
    State.kickOff(m)
    m.activePlayer, m.phase = "player", "summon"
    local def = H.give(m, "player", s.definition)
    T.eq(H.store(m):summonCard(def.id, "striker", 1, "attack"), true)
    T.eq(m.players.player.pitch.strikers[1].stamina, 4)
end)
