local T    = require("tests.t")
local Flow = require("ui.menu.flow")

T.test("flow starts on home with PLAY focused; Enter opens deck select", function()
    local f = Flow.new(3)
    T.eq(f.screen, "home"); T.eq(f.home.index, 1)
    T.eq(f:key("return"), nil); T.eq(f.screen, "decks")
end)

T.test("up/down wrap on home and Esc quits", function()
    local f = Flow.new(3)
    f:key("up");   T.eq(f.home.index, 3)
    f:key("down"); T.eq(f.home.index, 1)
    T.eq(f:key("escape"), "quit"); T.eq(f.screen, "home")
end)

T.test("CARD LIBRARY opens the library and closing returns home", function()
    local f = Flow.new(3)
    T.eq(f:activateHome(2), "openLibrary"); T.eq(f.screen, "library")
    T.eq(f:key("escape"), nil, "library keys belong to the library module")
    T.eq(f.screen, "library")
    f:closeLibrary(); T.eq(f.screen, "home")
end)

T.test("QUIT returns quit", function()
    local f = Flow.new(3)
    f:key("down"); f:key("down")
    T.eq(f:key("kpenter"), "quit")
end)

T.test("deck select: arrows clamp, Enter starts, Esc goes back home", function()
    local f = Flow.new(3)
    f:activateHome(1)
    f:key("left"); T.eq(f.decks.index, 1)
    f:key("right"); f:key("right"); f:key("right"); T.eq(f.decks.index, 3)
    local a, i = f:key("return"); T.eq(a, "start"); T.eq(i, 3)
    T.eq(f:key("escape"), nil); T.eq(f.screen, "home")
end)

T.test("clicking a deck selects it; clicking it again starts", function()
    local f = Flow.new(3)
    f:activateHome(1)
    T.eq(f:clickDeck(2), nil); T.eq(f.decks.index, 2)
    local a, i = f:clickDeck(2); T.eq(a, "start"); T.eq(i, 2)
    a, i = f:kickOff(); T.eq(a, "start"); T.eq(i, 2)
    f:back(); T.eq(f.screen, "home")
end)
