local T = require("tests.t")
local H = require("tests.helpers")

T.test("bug fix: the AI's Red Card does not fire on a tie", function()
    local m = H.match()
    H.place(m, "player", "striker", 1, H.card("striker", 1500, 500))
    H.place(m, "opponent", "defender", 1, H.card("defender", 900, 1500))
    H.trap(m, "opponent", "trap-red-card")
    local r = H.store(m):declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    T.eq(r.outcome, "tie")
    T.eq(#m.players.opponent.pitch.traps, 1)
end)

T.test("bug fix: the human's Red Card window does not open on a tie", function()
    local m = H.match({ active = "opponent" })
    H.place(m, "opponent", "striker", 1, H.card("striker", 1500, 500))
    H.place(m, "player", "defender", 1, H.card("defender", 900, 1500))
    H.trap(m, "player", "trap-red-card")
    local s = H.store(m)
    s:declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    T.eq(s.trapWindow, nil)
end)

-- Attacker: striker 2000. Defending side: keeper 1600 and an attack-mode midfielder that
-- can cover an empty defender slot.
local function coverBoard(attackerId)
    local defId = attackerId == "player" and "opponent" or "player"
    local m = H.match({ active = attackerId })
    H.place(m, attackerId, "striker", 1, H.card("striker", 2000, 500))
    H.place(m, defId, "keeper", 0, H.card("keeper", 300, 1600))
    H.place(m, defId, "midfielder", 0, H.card("midfielder", 1000, 1000))
    return m, H.store(m)
end

T.test("bug fix: after LET THROUGH, the AI's VAR overturns the goal", function()
    local m, s = coverBoard("player")
    H.trap(m, "opponent", "trap-var")
    local r = s:declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    T.eq(r.outcome, "cover_needed")
    s:resolveCover(nil)
    T.eq(m.players.opponent.lp, 4000)
    T.eq(#m.players.opponent.pitch.traps, 0)
    T.eq(m.players.player.pitch.strikers[1], nil)
end)

T.test("bug fix: after LET THROUGH, the human gets a VAR window for the AI's goal", function()
    local m, s = coverBoard("opponent")
    H.trap(m, "player", "trap-var")
    s:declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    s:resolveCover(nil)
    T.ok(s.trapWindow, "window open"); T.eq(s.trapWindow.type, "post_damage")
    s:resolveTrap(1)
    T.eq(m.players.player.lp, 4000)
    T.eq(m.players.opponent.pitch.strikers[1], nil)
end)

T.test("bug fix: a cover that loses its card gives the human a Red Card window", function()
    local m, s = coverBoard("opponent")
    H.trap(m, "player", "trap-red-card")
    s:declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    s:resolveCover(H.slot("midfielder"))
    T.ok(s.trapWindow, "window open"); T.eq(s.trapWindow.type, "post_destroy")
end)

T.test("bug fix: the AI's VAR also overturns a Direct Free Kick goal", function()
    local m = H.match()
    H.place(m, "player", "striker", 1, H.card("striker", 2000, 500))
    H.place(m, "opponent", "keeper", 0, H.card("keeper", 300, 1600))
    H.trap(m, "opponent", "trap-var")
    local card = H.give(m, "player", H.def("strat-direct-free-kick"))
    local r = H.store(m):playStrategy(card.id)
    T.eq(r.outcome, "damage")
    T.eq(m.players.opponent.lp, 4000)
    T.eq(m.players.player.pitch.strikers[1], nil)
end)

T.test("bug fix: the human gets a VAR window after the AI's Penalty goal", function()
    local m = H.match({ active = "opponent" })
    H.place(m, "opponent", "striker", 1, H.card("striker", 2000, 500))
    H.place(m, "player", "keeper", 0, H.card("keeper", 300, 1600))
    H.trap(m, "player", "trap-var")
    local card = H.give(m, "opponent", H.def("strat-penalty"))
    local s = H.store(m)
    s:playStrategy(card.id)
    T.ok(s.trapWindow, "window open"); T.eq(s.trapWindow.type, "post_damage")
    T.eq(s.trapWindow.damage, 400)
end)

-- Player attacks a DEF 2000 defender with an 1800 striker (and loses).
local function ldfBoard(targetMode, otherMode)
    local m = H.match()
    H.place(m, "player", "striker", 1, H.card("striker", 1800, 500))
    H.place(m, "opponent", "defender", 1, H.card("defender", 900, 2000), targetMode)
    if otherMode then H.place(m, "opponent", "defender", 2, H.card("defender", 900, 1900), otherMode) end
    H.trap(m, "player", "trap-last-defender-foul")
    return m, H.store(m)
end

T.test("bug fix: Last Defender Foul counts only face-up defenders", function()
    local _, s = ldfBoard("attack", "defense")
    s:declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    T.ok(s.trapWindow, "window open"); T.eq(s.trapWindow.type, "post_last_defender")
end)

T.test("bug fix: Last Defender Foul does not trigger on a tie", function()
    local m = H.match()
    H.place(m, "player", "striker", 1, H.card("striker", 2000, 500))
    H.place(m, "opponent", "defender", 1, H.card("defender", 900, 2000))
    H.trap(m, "player", "trap-last-defender-foul")
    local s = H.store(m)
    s:declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    T.eq(s.trapWindow, nil)
end)

T.test("bug fix: Last Defender Foul is not offered against a lone face-down defender", function()
    local _, s = ldfBoard("defense", nil)
    s:declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    T.eq(s.trapWindow, nil)
end)

T.test("bug fix: after the human passes Offside, the AI's goal still gets a VAR window", function()
    local m = H.match({ active = "opponent" })
    H.place(m, "opponent", "striker", 1, H.card("striker", 2000, 500))
    H.place(m, "player", "keeper", 0, H.card("keeper", 300, 1600))
    H.trap(m, "player", "trap-offside")
    H.trap(m, "player", "trap-var")
    local s = H.store(m)
    s:declareAttack(H.slot("striker", 1), H.slot("keeper"))
    T.eq(s.trapWindow.type, "pre_attack")
    s:resolveTrap(nil)
    T.ok(s.trapWindow, "VAR window open"); T.eq(s.trapWindow.type, "post_damage")
end)
