local T = require("tests.t")
local H = require("tests.helpers")

T.test("helpers: H.match gives empty boards and hands in the requested phase", function()
    local m = H.match({ turn = 3, phase = "summon", active = "opponent" })
    T.eq(#m.players.player.hand, 0); T.eq(#m.players.opponent.deck, 10)
    T.eq(m.players.player.pitch.keeper, nil); T.eq(m.turn, 3)
    T.eq(m.phase, "summon"); T.eq(m.activePlayer, "opponent")
end)

T.test("helpers: a placed board drives a real store attack", function()
    local m = H.match()
    H.place(m, "player", "striker", 1, H.card("striker", 2000, 500))
    H.place(m, "opponent", "defender", 1, H.card("defender", 900, 1500))
    local r = H.store(m):declareAttack(H.slot("striker", 1), H.slot("defender", 1))
    T.eq(r.outcome, "defender_destroyed"); T.eq(r.damage, 500)
    T.eq(m.players.opponent.lp, 3500)
    T.eq(m.players.opponent.pitch.defenders[1], nil)
end)
