local T      = require("tests.t")
local H      = require("tests.helpers")
local Combat = require("engine.combat")
local Phases = require("engine.phases")

-- Player: keeper 1500 + two defenders + a midfielder. Opponent: a striker and a midfielder.
local function setup()
    local m = H.match()
    local keeper = H.place(m, "player", "keeper", 0, H.card("keeper", 300, 1500))
    H.place(m, "player", "defender", 1, H.card("defender", 1600, 1500))
    H.place(m, "player", "defender", 2, H.card("defender", 900, 1500))
    H.place(m, "player", "midfielder", 0, H.card("midfielder", 1800, 1500))
    H.place(m, "opponent", "striker", 1, H.card("striker", 2000, 500))
    H.place(m, "opponent", "midfielder", 0, H.card("midfielder", 1000, 1000))
    return m, keeper, H.store(m)
end
local function keeperDef(m, keeper) return Combat.keeperEffectiveDef(keeper, m.players.player.pitch) end

T.test("keeper bonus: a defender that attacked stops counting during the opponent's turn", function()
    local m, keeper, s = setup()
    T.eq(keeperDef(m, keeper), 1500 + 600 + 150)
    s:declareAttack(H.slot("defender", 1), H.slot("striker", 1))
    Phases.endTurn(m)
    T.eq(m.activePlayer, "opponent")
    T.eq(keeperDef(m, keeper), 1500 + 300 + 150)
end)

T.test("keeper bonus: ...and counts again from the start of its owner's next turn", function()
    local m, keeper, s = setup()
    s:declareAttack(H.slot("defender", 1), H.slot("striker", 1))
    Phases.endTurn(m)
    Phases.endTurn(m)
    T.eq(m.activePlayer, "player")
    T.eq(keeperDef(m, keeper), 1500 + 600 + 150)
end)

T.test("keeper bonus: same timing for the midfielder's +150", function()
    local m, keeper, s = setup()
    s:declareAttack(H.slot("midfielder"), H.slot("midfielder"))
    Phases.endTurn(m)
    T.eq(keeperDef(m, keeper), 1500 + 600)
    Phases.endTurn(m)
    T.eq(keeperDef(m, keeper), 1500 + 600 + 150)
end)
