local T      = require("tests.t")
local Banner = require("ui.match.banner")

T.test("pose slides in from the left, holds, slides out right", function()
    local dx, a = Banner.pose(0);           T.near(dx, -Banner.SLIDE); T.near(a, 1)
    dx, a = Banner.pose(Banner.IN);         T.near(dx, 0);             T.near(a, 1)
    dx, a = Banner.pose(Banner.total());    T.near(dx, Banner.SLIDE, 1e-3); T.near(a, 0, 1e-6)
end)

T.test("a banner disappears after its total time", function()
    local b = Banner.new()
    b:show("X", "good")
    b:update(1.0); T.eq(b.text, "X")
    b:update(2.0); T.eq(b.text, nil)
end)

T.test("show restarts a running banner", function()
    local b = Banner.new()
    b:show("A"); b:update(1.0)
    b:show("B", "bad")
    T.eq(b.text, "B"); T.eq(b.kind, "bad"); T.near(b.t, 0)
end)

T.test("wide banners carry their own size and hold time", function()
    local b = Banner.new({ w = 1400, h = 84, y = 330, size = 46, hold = 2.4, slide = 1500 })
    T.eq(b.w, 1400); T.eq(b.y, 330); T.eq(b.size, 46)
    b:show("HALF TIME", "half")
    b:update(2.5); T.eq(b.text, "HALF TIME")
    b:update(0.6); T.eq(b.text, nil)
    local d = Banner.new(); T.eq(d.w, Banner.W); T.eq(d.hold, Banner.HOLD)
end)

T.test("pose honours a custom hold and slide", function()
    local dx = Banner.pose(Banner.IN + 2.3, 2.4, 1500); T.near(dx, 0)
    dx = Banner.pose(0, 2.4, 1500); T.near(dx, -1500)
    local _, a = Banner.pose(Banner.total(2.4), 2.4, 1500); T.near(a, 0, 1e-6)
end)
