local T  = require("tests.t")
local Fx = require("ui.overlay.trapfx")

T.test("purple flash fades while the card spins in and flips face-up", function()
    local p = Fx.pose(0)
    T.near(p.flash, 1); T.eq(p.scale, 0)
    p = Fx.pose(Fx.FLASH_DUR); T.near(p.flash, 0)
    p = Fx.pose(Fx.FLIP + Fx.FLIP_DUR * 0.25); T.ok(not p.faceUp); T.ok(p.spin < 0)
    p = Fx.pose(Fx.FLIP + Fx.FLIP_DUR * 0.75); T.ok(p.faceUp)
    p = Fx.pose(Fx.FLIP + Fx.FLIP_DUR)
    T.near(p.scale, 1); T.near(p.spin, 0); T.near(p.flipX, 1)
end)

T.test("the stamp slams from big to its resting size", function()
    T.eq(Fx.pose(Fx.STAMP - 0.01).stamp, 0)
    T.near(Fx.pose(Fx.STAMP).stampScale, Fx.STAMP_FROM)
    local p = Fx.pose(Fx.STAMP + Fx.STAMP_DUR)
    T.near(p.stampScale, 1); T.near(p.stampAlpha, 1)
end)

T.test("dust, ribbon, text and hint follow the stamp in order", function()
    T.ok(Fx.STAMP < Fx.DUST and Fx.DUST < Fx.RIBBON and Fx.RIBBON < Fx.TEXT and Fx.TEXT < Fx.HINT)
    T.eq(Fx.pose(Fx.DUST - 0.01).dust, 0)
    T.eq(Fx.pose(Fx.RIBBON - 0.01).ribbon, 0); T.near(Fx.pose(Fx.RIBBON + Fx.RIBBON_DUR).ribbon, 1)
    T.near(Fx.pose(Fx.TEXT - 0.01).text, 0);   T.near(Fx.pose(Fx.TEXT + Fx.TEXT_DUR).text, 1)
    T.near(Fx.pose(Fx.HINT + 0.25).hint, 1)
end)

T.test("headline and effect text", function()
    T.eq(Fx.headline("player"), "YOU ACTIVATED A TRAP")
    T.eq(Fx.headline("opponent"), "OPPONENT TRAP")
    T.eq(Fx.effectText({ ability = "OFFSIDE", abilityText = "x" }), "Striker attack cancelled — caught offside!")
    T.eq(Fx.effectText({ ability = "NEW", abilityText = "Does things." }), "Does things.")
    T.eq(Fx.effectText(nil), "")
end)

T.test("dust puffs spread out and fade", function()
    local a, b = Fx.dustPuffs(0.1, 8), Fx.dustPuffs(0.9, 8)
    T.eq(#a, 8)
    T.ok(math.abs(b[1].dx) > math.abs(a[1].dx)); T.ok(b[1].r > a[1].r); T.ok(b[1].a < a[1].a)
    T.ok(a[1].dx > 0 and a[8].dx < 0, "puffs go both ways")
end)
