local T     = require("tests.t")
local LPBar = require("ui.match.lpbar")

T.test("a new bar is settled", function()
    local b = LPBar.new(4000, 4000)
    T.eq(b.shown, 4000); T.eq(b.chunk, 4000)
    local f, c = b:ratios(); T.near(f, 1); T.near(c, 1)
end)

T.test("damage counts the number down to the target", function()
    local b = LPBar.new(4000, 4000)
    b:set(3000)
    b:update(0.3)
    T.ok(b.shown > 3000 and b.shown < 4000, "mid count-down: " .. b.shown)
    b:update(0.5)
    T.eq(b.shown, 3000)
end)

T.test("the white chunk lingers, then drains", function()
    local b = LPBar.new(4000, 4000)
    b:set(3000)
    b:update(0.3)
    T.near(b.chunk, 4000)
    b:update(0.7)
    T.near(b.chunk, 3000); T.eq(b.active, false)
end)

T.test("healing jumps instantly", function()
    local b = LPBar.new(3000, 4000)
    b:set(3500)
    T.eq(b.shown, 3500); T.near(b.chunk, 3500)
end)

T.test("a second hit mid-drain keeps the chunk where it was", function()
    local b = LPBar.new(4000, 4000)
    b:set(3000); b:update(0.5)
    local before = b.chunk
    b:set(2000)
    T.near(b.chunk, before); T.ok(b.chunk > 3000)
    b:update(2)
    T.eq(b.shown, 2000); T.near(b.chunk, 2000)
end)

T.test("ratios clamp to 0..1", function()
    local f, c = LPBar.new(-200, 4000):ratios()
    T.near(f, 0); T.near(c, 0)
end)
