local T     = require("tests.t")
local Hover = require("ui.match.hover")

T.test("hover shows only after the delay", function()
    local h = Hover.new(0.3)
    T.eq(h:update(0.1, "a"), false)
    T.eq(h:update(0.2, "a"), false)
    T.eq(h:update(0.15, "a"), true)
    T.ok(h:shown())
end)

T.test("a new key restarts the timer", function()
    local h = Hover.new(0.3)
    h:update(0, "a"); h:update(0.4, "a")
    T.ok(h:shown())
    T.eq(h:update(0.1, "b"), false)
    T.ok(not h:shown())
    T.eq(h:update(0.31, "b"), true)
end)

T.test("nil key hides and stays hidden", function()
    local h = Hover.new(0.3)
    h:update(0, "a"); h:update(0.5, "a")
    T.eq(h:update(0.1, nil), false)
    T.eq(h:update(1.0, nil), false)
    T.ok(not h:shown())
end)
