local T        = require("tests.t")
local H        = require("tests.helpers")
local Resolver = require("engine.cards.resolver")

T.test("resolver: keyword, has and hidden read pitched cards safely", function()
    local m = H.match()
    local c = H.place(m, "player", "striker", 1, H.kw("PACE", "striker", 2000, 500))
    T.eq(Resolver.keyword(c), "PACE")
    T.ok(Resolver.has(c, "PACE")); T.ok(not Resolver.has(c, "AERIAL"))
    T.eq(Resolver.keyword(nil), nil); T.ok(not Resolver.has(nil, "PACE"))
    local plain = H.place(m, "player", "striker", 2, H.card("striker", 2000, 500))
    T.eq(Resolver.keyword(plain), nil)
    local fd = H.place(m, "player", "defender", 1, H.card("defender", 900, 1900), "defense")
    T.ok(Resolver.hidden(fd)); T.ok(not Resolver.hidden(c)); T.ok(not Resolver.hidden(nil))
    fd.revealed = true
    T.ok(not Resolver.hidden(fd))
end)

T.test("resolver: fieldCards walks every slot, holes included", function()
    local m = H.match()
    H.place(m, "player", "striker", 2, H.card("striker", 2000, 500))
    H.place(m, "player", "defender", 2, H.card("defender", 900, 1900))
    H.place(m, "player", "keeper", 0, H.card("keeper", 300, 1800))
    local list = Resolver.fieldCards(m.players.player.pitch)
    T.eq(#list, 3)
    T.eq(list[1].slotType, "keeper")
    T.eq(list[2].slotType, "defender"); T.eq(list[2].index, 2)
    T.eq(list[3].slotType, "striker");  T.eq(list[3].index, 2)
    T.eq(#Resolver.fieldCards(nil), 0)
end)

T.test("resolver: trigger logs ability_triggered and collects the keyword on the result", function()
    local m = H.match()
    local c = H.place(m, "opponent", "defender", 1, H.kw("BOLT", "defender", 750, 1950), "defense")
    local result = {}
    Resolver.trigger(m, "opponent", c, "BOLT", { amount = 500 }, result)
    local t = H.triggers(m)
    T.eq(#t, 1)
    T.eq(t[1].player, "opponent"); T.eq(t[1].card, c.definition.id); T.eq(t[1].name, c.definition.name)
    T.eq(t[1].keyword, "BOLT"); T.eq(t[1].amount, 500); T.eq(t[1].hidden, true)
    T.eq(result.abilities[1], "BOLT")
end)
