return {
    { id="def-the-rock",           name="The Rock",             type="defender",   rarity="uncommon", stats={ atk=800,  def=2100 },
      keyword="IMMOVABLE",   keywordName="Immovable",
      abilityText="On a tie, attacking or defending, The Rock survives; only the other card is destroyed." },
    { id="def-destroyer",          name="The Destroyer",        type="defender",   rarity="common",   stats={ atk=900,  def=1900 },
      keyword="HARD_TACKLE", keywordName="Hard tackle",
      abilityText="A card that attacks it and isn't destroyed can't act on its owner's next turn." },
    { id="def-ball-playing",       name="Ball-Playing Defender",type="defender",   rarity="common",   stats={ atk=1400, def=1700 },
      keyword="BUILD_UP",    keywordName="Build-up",
      abilityText="When it wins a fight (destroys the other card and survives), you draw 1 card." },
    { id="def-stopper",            name="The Stopper",          type="defender",   rarity="uncommon", stats={ atk=850,  def=2000 },
      keyword="LAST_MAN",    keywordName="Last man",
      abilityText="+300 DEF while it is your only card in the defender slots." },
    { id="def-libero",             name="Libero",               type="defender",   rarity="rare",     stats={ atk=1600, def=1500 },
      keyword="SWEEPER",     keywordName="Sweeper",
      abilityText="May cover an empty defender or midfielder slot. Covering doesn't stop it acting on your next turn." },
    { id="def-pressing-back",      name="Pressing Back",        type="defender",   rarity="common",   stats={ atk=950,  def=1800 },
      keyword="INTERCEPT",   keywordName="Intercept",
      abilityText="May also cover an empty defender slot (normal cover rules)." },
    { id="def-catenaccio-anchor",  name="Catenaccio Anchor",   type="defender",   rarity="uncommon", stats={ atk=750,  def=1950 },
      keyword="BOLT",        keywordName="Bolt",
      abilityText="Counts +500 (instead of +300) toward your keeper's effective DEF." },
}
