return {
    {
        id          = "form-tiki-taka",
        name        = "Tiki-Taka (4-3-3)",
        type        = "formation",
        rarity      = "rare",
        tags        = { "possession" },
        stats       = {},
        maxPerDeck  = 2,
        slotConfig  = { defenders = 3, midfielders = 1, strikers = 2 },
        abilityText = "Midfield control bonus: draw 1 card after each successful striker attack this turn.",
        ability     = "TIKI_TAKA_BONUS",
    },
    {
        id          = "form-long-ball",
        name        = "Long Ball (4-4-2)",
        type        = "formation",
        rarity      = "rare",
        tags        = { "direct" },
        stats       = {},
        maxPerDeck  = 2,
        slotConfig  = { defenders = 4, midfielders = 1, strikers = 2 },
        abilityText = "Midfield control bonus: each striker attack gets +200 ATK this turn.",
        ability     = "LONG_BALL_BONUS",
    },
    {
        id          = "form-catenaccio",
        name        = "Catenaccio (5-3-2)",
        type        = "formation",
        rarity      = "rare",
        tags        = { "defensive" },
        stats       = {},
        maxPerDeck  = 2,
        slotConfig  = { defenders = 4, midfielders = 1, strikers = 1 },
        abilityText = "Midfield control bonus: all defenders gain +200 DEF this turn.",
        ability     = "CATENACCIO_BONUS",
    },
    {
        id          = "form-gegenpress",
        name        = "Gegenpress (4-2-3-1)",
        type        = "formation",
        rarity      = "rare",
        tags        = { "pressing" },
        stats       = {},
        maxPerDeck  = 2,
        slotConfig  = { defenders = 4, midfielders = 1, strikers = 2 },
        abilityText = "Midfield control bonus: all attacking cards get +150 ATK. After turn 6: -200 ATK/DEF to all your cards.",
        ability     = "GEGENPRESS_BONUS",
    },
    {
        id          = "form-total-football",
        name        = "Total Football (3-5-2)",
        type        = "formation",
        rarity      = "rare",
        tags        = { "flexible" },
        stats       = {},
        maxPerDeck  = 2,
        slotConfig  = { defenders = 3, midfielders = 1, strikers = 2 },
        abilityText = "Midfield control bonus: move one pitched card to any empty slot for free this turn.",
        ability     = "TOTAL_FOOTBALL_BONUS",
    },
    {
        id          = "form-counter-attack",
        name        = "Counter-Attack (4-5-1)",
        type        = "formation",
        rarity      = "rare",
        tags        = { "reactive" },
        stats       = {},
        maxPerDeck  = 2,
        slotConfig  = { defenders = 4, midfielders = 1, strikers = 1 },
        abilityText = "Midfield control bonus: if your first striker attack this turn fails, that striker is not exhausted.",
        ability     = "COUNTER_ATTACK_BONUS",
    },
}
