return {
    { id="mid-box-to-box",          name="Box-to-Box",           type="midfielder", rarity="common",   stats={ atk=1800, def=1500 },
      keyword="ENGINE",        keywordName="Engine",
      abilityText="In your midfielder slot, in either mode: +100 ATK to your striker-slot cards and +100 DEF to your defender-slot cards (instead of the normal +200)." },
    { id="mid-deep-lying-playmaker",name="Deep-Lying Playmaker",  type="midfielder", rarity="common",   stats={ atk=1500, def=1700 },
      keyword="METRONOME",     keywordName="Metronome",
      abilityText="When it gives you midfield control at the start of your turn, you also get +1 summon that turn." },
    { id="mid-pressing-monster",    name="Pressing Monster",      type="midfielder", rarity="common",   stats={ atk=1700, def=1400 },
      keyword="COUNTER_PRESS", keywordName="Counter-press",
      abilityText="+300 DEF when it covers an empty slot." },
    { id="mid-creative-playmaker",  name="Creative Playmaker",    type="midfielder", rarity="rare",     stats={ atk=1600, def=1550 },
      keyword="THROUGH_BALL",  keywordName="Through ball",
      abilityText="Once per turn, one of your striker-slot cards may shoot at the enemy keeper even when both enemy defender slots are filled." },
    { id="mid-direct-support",      name="Direct Support",        type="midfielder", rarity="common",   stats={ atk=1650, def=1450 },
      keyword="OVERLAP",       keywordName="Overlap",
      abilityText="In your midfielder slot in attack mode, your striker-slot cards get +300 ATK instead of +200." },
}
