return {
    {
        id          = "strat-direct-free-kick",
        name        = "Direct Free Kick",
        type        = "strategy",
        rarity      = "common",
        tags        = { "direct" },
        stats       = {},
        maxPerDeck  = 3,
        abilityText = "Your highest ATK striker slot card attacks the keeper directly this turn regardless of defenders. Keeper effective DEF still includes active defender bonuses. Striker is exhausted after the shot.",
        ability     = "DIRECT_FREE_KICK",
    },
    {
        id          = "strat-penalty",
        name        = "Penalty",
        type        = "strategy",
        rarity      = "rare",
        tags        = { "direct" },
        stats       = {},
        maxPerDeck  = 1,
        abilityText = "Your highest ATK striker slot card attacks the keeper directly. Keeper defends at BASE DEF only — active defender and midfielder bonuses do not apply. Striker is exhausted after the shot.",
        ability     = "PENALTY",
    },
    {
        id          = "strat-scout-report",
        name        = "Scout Report",
        type        = "strategy",
        rarity      = "common",
        tags        = { "information" },
        stats       = {},
        maxPerDeck  = 3,
        abilityText = "Reveal one opponent face-down card. It stays revealed — face-up for both players but still in defense mode. No combat or activations triggered.",
        ability     = "SCOUT_REPORT",
    },
    {
        id          = "strat-time-wasting",
        name        = "Time Wasting",
        type        = "strategy",
        rarity      = "rare",
        tags        = { "control" },
        stats       = {},
        maxPerDeck  = 1,
        abilityText = "Only when your LP is higher than your opponent's LP: opponent can only summon 1 card instead of 2 on their next turn.",
        ability     = "TIME_WASTING",
    },
    {
        id           = "strat-substitution",
        name         = "Substitution",
        type         = "strategy",
        rarity       = "uncommon",
        tags         = { "tempo" },
        stats        = {},
        maxPerDeck   = 3,
        activationPhase = "summon_or_response",
        abilityText  = "Play during your summon phase, OR during your attack phase in response to an opponent targeting one of your cards. Return that card to your hand. Immediately summon one card from your hand to that slot — does not cost a summon. The returned card cannot be resummoned this turn.",
        ability      = "SUBSTITUTION",
    },
}
