return {
    { id="str-target-man",       name="The Target Man",      type="striker",    rarity="common",   stats={ atk=2200, def=600  },
      keyword="AERIAL",       keywordName="Aerial",
      abilityText="Offside can't be activated against this card's attacks." },
    { id="str-poacher",          name="The Poacher",         type="striker",    rarity="common",   stats={ atk=2100, def=500  },
      keyword="OPPORTUNIST",  keywordName="Opportunist",
      abilityText="+400 ATK on shots while at least one enemy defender slot is empty." },
    { id="str-speed-demon",      name="Speed Demon",         type="striker",    rarity="common",   stats={ atk=2150, def=550  },
      keyword="PACE",         keywordName="Pace",
      abilityText="Can attack on the turn it is summoned (attack mode only)." },
    { id="str-clinical-finisher",name="Clinical Finisher",   type="striker",    rarity="rare",     stats={ atk=2300, def=600  },
      keyword="CLINICAL",     keywordName="Clinical",
      abilityText="A shot that exactly ties the keeper's DEF is a goal for 300 LP instead of a tie." },
    { id="str-pacy-winger",      name="Pacy Winger",         type="striker",    rarity="common",   stats={ atk=2050, def=500  },
      keyword="BEAT_THE_MAN", keywordName="Beat the man",
      abilityText="Its attacks into empty slots can't be covered." },
    { id="str-fox-in-the-box",   name="Fox in the Box",      type="striker",    rarity="uncommon", stats={ atk=2150, def=650  },
      keyword="INSTINCT",     keywordName="Instinct",
      abilityText="+300 ATK on shots while the defending keeper is exhausted." },
    { id="str-complete-forward", name="Complete Forward",    type="striker",    rarity="uncommon", stats={ atk=2150, def=900  },
      keyword="LINK_UP",      keywordName="Link-up",
      abilityText="While it is on your pitch, your other striker-slot cards get +150 ATK." },
    { id="str-pressing-forward", name="Pressing Forward",    type="striker",    rarity="common",   stats={ atk=2100, def=700  },
      keyword="PRESS",        keywordName="Press",
      abilityText="When summoned (either mode): exhaust one enemy defender-slot card, the face-up one with the highest DEF if any. It can't cover this turn." },
}
