return {
    {
        id           = "trap-var",
        name         = "VAR",
        type         = "trap",
        rarity       = "rare",
        tags         = {},
        stats        = {},
        trapCategory = "A",
        maxPerDeck   = 1,
        abilityText  = "Mode 1 (on keeper LP damage): Negate the damage. Attacking striker returned to opponent's hand — they must use a summon to resummon it.\nMode 2 (on opponent Red Card): Negate the Red Card. Targeted card survives.",
        ability      = "VAR",
    },
    {
        id           = "trap-offside",
        name         = "Offside",
        type         = "trap",
        rarity       = "common",
        tags         = {},
        stats        = {},
        trapCategory = "A",
        maxPerDeck   = 3,
        abilityText  = "When an opponent's striker slot card declares an attack: cancel that attack. Striker is exhausted but not destroyed. Cannot activate against midfielder attacks or covering.",
        ability      = "OFFSIDE",
    },
    {
        id           = "trap-red-card",
        name         = "Red Card",
        type         = "trap",
        rarity       = "uncommon",
        tags         = {},
        stats        = {},
        trapCategory = "A",
        maxPerDeck   = 2,
        abilityText  = "When an opponent's card destroys one of your cards in combat: that card is also destroyed permanently. One for one trade. Can be negated by VAR or Manager's Challenge.",
        ability      = "RED_CARD",
    },
    {
        id           = "trap-last-defender-foul",
        name         = "Last Defender Foul",
        type         = "trap",
        rarity       = "rare",
        tags         = {},
        stats        = {},
        trapCategory = "A",
        maxPerDeck   = 2,
        abilityText  = "When your opponent's LAST active defender destroys your attacking card: that defender is permanently destroyed. Your next striker attack this turn bypasses covering. Cannot activate if opponent has more than one active defender.",
        ability      = "LAST_DEFENDER_FOUL",
    },
    {
        id           = "trap-managers-challenge",
        name         = "Manager's Challenge",
        type         = "trap",
        rarity       = "rare",
        tags         = {},
        stats        = {},
        trapCategory = "A",
        maxPerDeck   = 1,
        abilityText  = "When any opponent trap card is activated: negate it completely (goes to discard, no effect). Cost: pay 1000 LP immediately. Can negate any trap including VAR and Red Card.",
        ability      = "MANAGERS_CHALLENGE",
    },
}
